### ISSUE TITLE
Fallback wallpaper

### ISSUE THREAD

**Issue by anu-rock** [lpikora/bing-wallpaper-daily-mac-multimonitor#2]
On some days Bing's picture of the day is not available for downloading, as can be seen in the screenshot below. Your bash script tries to download the image per the resolution of the user's monitor. When Bing has downloading disabled, only lower resolution URLs of the image work and higher ones (eg. 1900x1200) do not.

<a href="https://ibb.co/Q9gB3ws"><img src="https://i.ibb.co/6YMh7C6/Bing-Picture-Download-Disabled.jpg" alt="Bing-Picture-Download-Disabled" border="0"></a>

But when this happens, we are treated with a wallpaper that is a nasty placeholder image as seen below.

<a href="https://imgbb.com/"><img src="https://i.ibb.co/j4sPRwX/placeholder-image.png" alt="placeholder-image" border="0"></a>

It would be great if you could offer a quick and reliable way to choose a fallback wallpaper from the local disk when this happens.

**Comment by lpikora** [comment]
Hi, thank you for your feedback. I will try to implement what you suggest like:

- get image with desired resolution

when image is successfully downloaded:
- set as desktop image on all monitors

when image can't be downloaded in desired resolution:
- try download image in different resolution
- when image cant be downloaded, keep the current desktop image

**Comment by anu-rock** [comment]
@lpikora Very well put. Makes perfect sense. Thank you :)
