### ISSUE TITLE
Feature request: insert mkt={ }

### ISSUE THREAD

**Issue by flumignan** [lpikora/bing-wallpaper-daily-mac-multimonitor#6]
I'd like to request the option to choose the market for the download. For example, `en-US` or `en-WW` or the like.

**Comment by lpikora** [comment]
Hi, great idea. Thank you for the suggestion.

Image url have to be taken from https://www.bing.com/HPImageArchive.aspx?format=xml&idx=0&n=1&mkt=en-US instead of scraping bing.com also.

I will definitely try to implement it when I have some free time.

Or I'm open for pull request :)

**Comment by lpikora** [comment]
I have released new version of script with support for market/country parameter.

https://github.com/lpikora/bing-wallpaper-daily-mac-multimonitor/releases/tag/v1.2.0
