### ISSUE TITLE
Setting the wallpaper on all desktops/"spaces"

### ISSUE THREAD

**Issue by alexanderadam** [lpikora/bing-wallpaper-daily-mac-multimonitor#8]
Currently the script switches the wallpaper only on the current desktop/"space".
It would be great if it would be changed consistently amongst all instances.

**Comment by getzpas** [comment]
Yes, I agree. And even better: use different wallpapers amongst all desktops/spaces (newest on 1 desktop, yesterdays on 2 desktop, etc.), if somehow possible.

**Comment by gelpenaddict** [comment]
Updating to newest on all open desktops would be great.

**Comment by gelpenaddict** [comment]
My workaround for now:
- create a new desktop on main screen (uses Bing wallpaper)
- drag the new desktop to 2nd screen
- close desktops with old wallpaper on 2nd screen

Same with multiple desktops on main screen; create new one and close old ones.

**Comment by lpikora** [comment]
I have released new version of script with `--all-desktops-experimental` parameter. It will set wallpaper on all currently opened desktops and monitors. Only drawback is that it restarting Dock application and will remove all minimised apps from dock. It can be partially solved by checking `Minimise windows into application icon` in Dock Preferences.

https://github.com/lpikora/bing-wallpaper-daily-mac-multimonitor/releases/tag/v1.2.0
